# Generated by Django 3.1 on 2020-08-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='image_name',
        ),
    ]
