# Generated by Django 3.1 on 2020-08-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0002_auto_20200820_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.ImageField(upload_to='images', verbose_name='Изображение'),
        ),
    ]
