# Generated by Django 3.1 on 2020-08-22 11:50

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0003_auto_20200822_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='image_height', null=True, upload_to='images', verbose_name='Изображение', width_field='image_width'),
        ),
    ]
