# Generated by Django 3.1 on 2020-08-28 10:38

from django.db import migrations, models
import image_resize.storage
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0004_auto_20200822_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_original',
            field=models.ImageField(blank=True, null=True, upload_to='images/original', verbose_name='Оригинальное изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field='image_height', null=True, storage=image_resize.storage.OverwriteStorage(), upload_to='images', verbose_name='Изображение', width_field='image_width'),
        ),
    ]
